# Generated by Django 4.1.2 on 2022-10-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='1280px-CFR_050_locomotive.jpg', upload_to='media/blog/posts'),
        ),
    ]
